# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#Commited by bhagabat

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'

//hello bhagu comment -again commit---again--again---again//
//hello bhagu comment -again commit---again--again---again//
//<h2> Hello Bhagabat ...you are rock...your first deployment in final 2 production.</h2>
//<h2> Hello Bhagabat ...you are rock...your first deployment in final 2 production.</h2>
//<h2> Hello Bhagabat ...you are rock...your first deployment in final 2 production.</h2>

//<h2> Hello Bhagabat ...you are rock...your first deployment in final 2 production.</h2>
